add routine backup to S3
mongulu-cm/manzi-mfa pull request #30
Opened 2023-10-26 23:24 UTC by tsafacjo

2023-10-27 07:04 UTC, billmetangmo requested changes
Super boulot.

Dans les choses à faire pour merge, il faudrait juste modifier ton commit pour qu il suive la nomenclature commitlint et rajoutez le numéro de l issue entre parenthèses avec #.

*Sinon dans ce que je vois mais ça peut être fait ultérieurement:*
- le build et push de l image dans la CI
- utiliser plutôt le docker registre github ghct.io associé au collectif que le docker hub

2023-10-27 07:08 UTC, billmetangmo commented
Visiblement, le pricing du github package est trop bas. 500 moi de stockage par mois et 1 go de transfert https://docs.github.com/fr/billing/managing-billing-for-github-packages/about-billing-for-github-packages

Dans ce cas, ce serait plutôt pour moi de créer un docker registre mongulu-cl avec le compte du collectif collectif@mongulu.cm et y push l image

2023-11-01 10:13 UTC, tsafacjo commented
le builb fonctionne en local mais pas sur la ci.
Very strange !
Si tu as un peu de temps , je suis preneur pour ton expetise.

2024-02-17 19:03 UTC, billmetangmo commented
J'ai installé les self-hosted runners donc il y a plus d'erreurs de build , tu pourras continnuer ou tu t'e sarrete à @tsafacjo

2024-06-23 18:17 UTC, billmetangmo commented
- [ ] Add eroor in case cronjob failed

2024-07-04 21:29 UTC, merged