add notifications
mongulu-cm/manzi-mfa pull request #37
Opened 2023-11-05 15:48 UTC by tsafacjo

for now I send notification only to student 

The job run every two hours and send sms to those that are a meet within the next 2hours.  

Remind part send sms to Referent and add the ci/cd part

2023-11-05 16:12 UTC, tsafacjo commented
https://blog.thesparktree.com/docker-multi-arch-github-actions

2024-02-17 18:52 UTC, billmetangmo commented on notifications/notifier/__pycache__/sms_notifier.cpython-311.pyc
A supprimer

2024-02-17 18:56 UTC, billmetangmo commented on notifications/notifcations_cron_deployement.yml
> +            image: tsafacjo/sms_notifications:0.6
L'image doit être stocké dans le repo du collectif https://hub.docker.com/repositories/mongulu , les identifiant sosnt dans zulip.

2024-02-17 19:01 UTC, billmetangmo requested changes
Good work @tsafacjo . Reste plus qu'à corriger les commentiaresci-dessous et ajoutezdans le README les commandes pour build/push l'image et démarrer le cronjob.

Je n'ai cependant pas pu faire un test grandeur nature car j'arrive plus à installer httpSMS sur mon tel, il semble qu'il y ait un pb avec xiaomi ... ça marchait sur huawei ... donc j'ai dans l'immédiat recréditer Twilio et mis à jour le step pipdream pour supporter l'envoi de SMS 2 h avant en utilisant le day: https://pipedream.com/@mongulu/workflows

On va néanmoins merger ce code comme ça on pourra revenir dessus quand ce sera bon coté xiaomi

2024-03-17 14:35 UTC, billmetangmo commented
Avec la dernière AMJ Xiaomi c'est bon. J'ai modifié dans pipedream pour utiliser http sms

2024-06-20 20:38 UTC, closed without merging